language: python
dist: xenial
python:
  - "3.8"
# command to install dependencies
install:
  - pip install pipenv
  - pipenv install
  - pipenv install --dev
# command to run tests
script:
  - pytest --cov=ray
after_success:
  - coveralls

deploy:
  provider: pypi
  user: __token__
  password: 
    secure: Ec65J23L6AVpXEc32GEE72mSdmwvWrnV3M4KpvBB9a7xSsWn1ZbshBSsWrmY4oUOSQhHX10T0aboAuSAcYjFTsqVJn98ulxQNZ44vUQeOX9heldEV3wJi7OdJbU3HjkQXqDiJCahBndHlkG5M4Bw3kqP69jc9xuupd8mvUIPlCUn6hebCHLPcIfiSiTzbKuOPrfYjYEWHBUNtz3jInWKn+oYxH0Fhm3LpmasyZ3z1AvvA13GbLQ6svDS1+nyKKo2YIMGazYLWFtAmRf2Sq+BY2+ZhTBBXo68L7t7vJk6n4AJgGfGTpQd8fFhJMml9mRUsLkOIorZtzjtBLGBwFa+a3x/goYr8PWKhH9W8hTYLHWYTxJJIiJhgAMxjdsYA2fqq2lxw57lcmduh5MhOajrwISkH25uzx9YT+5yanwtsvH4Ntdv021o7BJo1aNApF22zvFs6SY/qj/296LgkIPhCNhcft1KctqQG0QmNx/43D3/G8yBR77Qp6ZZ9j5/lL4qm7y8t4r0XvRG1/4IXQs86FCoLffkDyEe+cPm86Zx8MFBkjxGcPqo8RdWS+3Ly1E/kystFwpQ0tKq7+hcxXduxt61FmxIiaqe0V3rmhniWtqDQ4FC/m7v5V4mTWZNBc7b3vyVebaG6dRbb7qauBwab9WtP50l2XVSSxKwwmqEM/Y=
  on:
    branch: master